version: '3'
services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile-frontend
    ports:
      - "5173:5173"  # Expose the frontend on port 5173
    depends_on:
      - backend  # Ensure the backend service is started first

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile-backend
    ports:
      - "8080:8080"  # Expose the backend on port 8080